- R/qgis-arguments.R
- tests/testthat/test-qgis-arguments.R
It seems more reasonable to use geopackage to pass data from R memory to QGIS processing. Shapefile has some limitations that may cause errors [http://switchfromshapefile.org/](http://switchfromshapefile.org/). Especially the 10 characters limit on the column names can be problematic.
For rasters, if the object actually stores a filename and it's of known type, the filename can be passed directly. This avoids unnecessary storage of potentially large data. I tested it and if the data are manually edited then the raster object does no longer provide the filename. It thus seems safe to do this.
This example.
```
f <- system.file("external/test.grd", package="raster")
f
r <- raster(f)
r@file@name
```
Here the filename exists.
```
values(r) <- 1:ncell(r) 
r@file@name
```
After the edit, the …
> minor improvements to passing data to QGIS

- R/qgis-configure.R
So here we go again... in some QGIS versions under Windows, it happens that the first line of output of qgis_run() is the working directory, hence, qgis_query_version() fails. Therefore, I slightly rewrote qgis_query_version() so that it looks for the QGIS version in all lines of the output of qgis_run().
> qgis_query_version(): search for qgis version in all output lines

- R/qgis-algorithm.R
- tests/testthat/test-qgis-algorithm.R
Thanks to qgis/QGIS#40287 multiple input arguments are now accepted by `qgisprocess`. This PR slighly adjusts `qgis_run_algorithm()` to make them also work from within R. I have already successfully tested this using the QGIS nightly build (3.17.0-Master). However, so far this only works if only one of the arguments is of type multipleinput. I am not sure if there are QGIS geoalgorithms which have two or more arguments of type multipleinput.
Pls note that when using the QGIS nightly version, the first line of `qgis_run()` returns again the current working directory under Windows, hence, it would be desirable to adjust `qgis_configure()` accordingly (see #32).
> make multiple input arguments work

- R/qgis-configure.R
A new regex was used to match the name of QGIS version when uses non-ascii characters. I tested in Windows 10 and Linux Ubuntu 20.04 with good results!
> fixed regex to match qgis version in qgis_query_version()

- DESCRIPTION
- R/compat-raster.R
- R/compat-sf.R
- tests/testthat/test-compat-raster.R
- tests/testthat/test-compat-sf.R
Solves two input types (crs, extent) from list in #13.
Includes tests.
> Add support for QGIS crs and extent

- R/qgis-algorithm.R
Hi! As per my comment [here](https://github.com/paleolimbot/qgisprocess/pull/33#issuecomment-843005659) and following #25  I made some changes to the multiple input implementation to correctly subset the arguments according to R syntax.
The problem was that multiple inputs were matched only to the first input and not to all of them. E.g.
`LAYERS = v_1, LAYERS = v_2, LAYERS = v_3` was passed as `LAYERS = v_1, LAYERS = v_1, LAYERS = v_1`.
Passed the tests locally, so hopefully it works! Cheers!
> Handle multiple inputs as lists with duplicated names in R.

- R/qgis-configure.R
- R/zzz.R
Currently we get:
```r
> library(qgisprocess)
Using 'qgis_process' at '/usr/bin/qgis_process'.
Run `qgis_configure()` for details.
> qgis_configure()
getOption('qgisprocess.path') was not found.
Trying Sys.getenv('R_QGISPROCESS_PATH'): '/usr/bin/qgis_process'
Success!
```
These are fine messages of course, but as a user I was curious why `qgis_configure()`, hence also `library(qgisprocess)` takes multiple seconds to finish, even after setting `R_QGISPROCESS_PATH`.  It seemed that `qgis_configure()` still took some seconds to finish after 'Success!' being printed. The explanation is simple from the code; the step that takes most time appears to be `qgis_algorithms(query = TRUE)`. So here's a suggestion to make this a little more explicit in the messages, which I think will make the user …
> More informative startup & config messages

- R/compat-sf.R
- tests/testthat/test-compat-sf.R
This allows passing point as input parameter to QGIS. Point is accepted as `sfc` with length 1 and geometry type `POINT`, so that user can also pass CRS, or as `POINT` without CRS.
Includes tests.
> Implementation of Point argument

- R/qgis-arguments.R
- tests/testthat/test-qgis-arguments.R
This tries to solve #75. Because in `qgis_sanitize_arguments()`, the step that matches user arguments against algorithm arguments drops the special `ELLIPSOID` and `PROJECT_PATH` arguments, the latter were not passed to the `qgis_process` command.
@thierryO can you give this a try?
> qgis_sanitize_arguments(): fix loss of special arguments

- R/qgis-detect.R
Fixes #81:
```r
> qgis_configure()
getOption('qgisprocess.path') was not found.
Sys.getenv('R_QGISPROCESS_PATH') was not found.
Trying 'qgis_process' on PATH
Error in processx::run("cmd.exe", c("/c", "call", path, args), ...): System command 'cmd.exe' failed, exit status: 1, stderr:
E> 'qgis_process' is not recognized as an internal or external command,
E> operable program or batch file.
Found 1 QGIS installation containing 'qgis_process':
C:/Program Files/QGIS 3.16/bin/qgis_process-qgis-ltr.bat
Trying command 'C:/Program Files/QGIS 3.16/bin/qgis_process-qgis-ltr.bat'
Success!
QGIS version: 3.16.16-Hannover
Saving configuration to 'C:\Users\FLORIS~1\AppData\Local/R-qgisprocess/R-qgisprocess/Cache/cache-0.0.0.9000.rds'
Metadata of 984 algorithms queried and stored in cache.
Run …
```
> qgis_detect_windows(): also search for qgis_process LTR

- R/qgis-help.R
- tests/testthat/test-qgis-help.R
For some algorithms, the `type` element in each parameter of `qgis_help(algorithm)$parameters` is a string instead of a list with an `id` element, and could probably serve as `id` directly. This causes issue #85 when running `qgis_arguments()`, i.e. when `qgisprocess.use_json_output = TRUE`.
This PR tries to fix #85 by taking those cases into account; an internal function is added to extract elements from the `type` element, and is used instead of applying `[[`.
A test has been added to include the result for `qgis:executesql`.
Current result (`INPUT_QUERY` is the parameter where it went wrong):
```r
> qgis_arguments("qgis:executesql")
name                 description        qgis_type default_value available_values acceptable_valu…
<chr>                <chr>              <chr>     <list> …
```
> qgis_arguments(): support character type element

- R/qgis-configure.R
This turns the message from #95 into:
```r
> qgis_path(query = TRUE, quiet = FALSE)
getOption('qgisprocess.path') was not found.
Sys.getenv('R_QGISPROCESS_PATH') was not found.
Trying 'qgis_process' on PATH...
'qgis_process' is not available on PATH.
Found 1 QGIS installation containing 'qgis_process':
C:/Program Files/QGIS 3.16/bin/qgis_process-qgis-ltr.bat
Trying command 'C:/Program Files/QGIS 3.16/bin/qgis_process-qgis-ltr.bat'
Success!
[1] "C:/Program Files/QGIS 3.16/bin/qgis_process-qgis-ltr.bat"
```
> qgis_query_path(): turn error into neutral msg (fixes #95)

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
This will fix the failing tests in #105; the '2021' signing key was still in use but has presumably expired. Switched to the key currently advertised at qgis.org.
Merging right away, since this fix succeeded in a dummy fork (https://github.com/florisvdh/qgisprocess/pull/1).
> GHA workflows: update QGIS Signing Key

- DESCRIPTION
- R/qgis-configure.R
- man/qgisprocess-package.Rd
- tests/testthat/test-qgis-configure.R
Attempt to fix #103.
- `qgis_query_version()`: fix the `abort()` message in case the version regex doesn't match
- `qgis_query_version()`: use a new regex, still depending on `qgis_process`'s output formatting with the version within parentheses and including a hyphen
- updating the test for `qgis_version()`, based on this regex and allowing versions up to QGIS 99.x :slightly_smiling_face:
- adding a test for `qgis_query_version()`
You can install this development version by running `remotes::install_github("paleolimbot/qgisprocess@5bd5f0b")`.
Please respond whether this fixes #103.
I get:
```r
> qgis_query_version()
[1] "3.26.1-Buenos Aires"
```
``` r
qgisprocess::qgis_configure()
#> getOption('qgisprocess.path') was not found.
#> Trying Sys.getenv('R_QGISPROCESS_PATH'): …
```
> qgis_query_version(): support version codenames with a whitespace

- R/qgis-configure.R
- R/zzz.R
Fixes #94, fixes #109.
Please feel free to suggest improvements.
When a cache is going to be used, the QGIS version is first compared between the cache version and that of the program in the path defined by the cache. It makes the package take a little more time to load, but this seems worth it, since conflicts are expected (outdated cached algorithms) if a version change at the same location is not captured.
If versions differ, the cache will not be used and a new cache is built. Startup messages make this clear. The reprex below first overwrites an existing cache rds file, in order to mimic an outdated cache upon loading **qgisprocess**.
``` r
suppressPackageStartupMessages(library(qgisprocess))
cache_data_file <- qgisprocess:::qgisprocess_cache$loaded_from …
```
> Check for QGIS version & path changes; update messages

- tests/testthat/test-compat-sf.R
- tests/testthat/test-qgis-run-algorithm.R
- tests/testthat/test-qgis-run-algorithm2.R
This PR mainly focuses on `test-qgis-run-algorithm.R`:
- for QGIS >= 3.23, run this file twice, once with and once without the JSON input method. This is arranged by a separate test file `test-qgis-run-algorithm2.R` that temporarily flips the JSON input setting and re-runs `test-qgis-run-algorithm.R`.
- the output of `test_local()` and `test_file()` are cleaned: before, the `qgis_run_algorithm()` tests wrote various `qgis_process` output to the console, e.g.:
<details><summary><strong>Extract from previous <code>test_local()</code> output</strong> (click to expand)</summary>
```
✔ |        11 | qgis-output [7.3s]                                                             
✔ |        15 | qgis-result [1.8s]                                                             
⠴ |         6 | …
```
> qgis_run_algorithm() tests: run them both with and without JSON input method

- .github/workflows/R-CMD-check.yaml
- README.Rmd
- README.md
This replaces hardcoded references to `master` by `main`, or adds them, where needed. Fixes #113.
When default branch `main` is ready (renaming of `master`), base branch of this PR + PR #31 needs to be flipped too.
Alternative is to first merge this in `master`, then rename default as `main` in GH.
> Prepare switching default branch from master to main

- R/qgis-configure.R
- tests/testthat/test-qgis-configure.R
This PR extends the reported and cached QGIS version string with the corresponding commit hash from the QGIS code repository, on condition that a development version is in use. Consequently, the cache will be rebuilt when switching to another development version (commit hash) of QGIS.
Currently, the labelling with the commit hash is triggered by the label 'Master' or the fact that the 'minor' part of the version number is odd.
```r
> qgis_version()
[1] "3.28.1-Firenze"
> options(qgisprocess.path = "/home/floris/git_repositories2/QGIS/build2/output/bin/qgis_process")
> suppressMessages(qgis_configure())
> qgis_version()
[1] "3.29.0-Master, development state cfbf5ef5"
> options(qgisprocess.path = "/home/floris/git_repositories2/QGIS/build3/output/bin/qgis_process")
> …
```
> Enhance detection and representation of QGIS development versions

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- DESCRIPTION
- R/qgis-configure.R
- tests/testthat/test-compat-raster.R
- tests/testthat/test-compat-stars.R
- tests/testthat/test-qgis-result.R
- tests/testthat/test-qgis-run-algorithm.R
Mainly:
- drop some packages from `Suggests`: **covr** and **fs**. The first is installed explicitly in GH Actions and not used elsewhere, the second was used in just one test and has been replaced.
- tests: drop some `skip_*` statements from tests where it's unneeded; reactivate a Windows test.
- This is also done in preparation of the retirement of **rgdal**, which is still in `Suggests` (currently still needed by `raster::crs` in two tests, but that should change in future since **raster** is scheduled to call **terra** instead of **rgdal** in such cases).
- update GHA workflows:
- reflect updates in r-lib/actions
- use latest Ubuntu LTS
- more future-proof APT key management for the Ubuntu jobs, i.e. storing keys in `/etc/apt/keyrings` and referring accordingly (not doing this …
> Various maintenance updates

- .github/workflows/R-CMD-check.yaml
- tests/testthat/test-qgis-run-algorithm.R
This PR addresses several problems described in https://github.com/paleolimbot/qgisprocess/pull/118#issuecomment-1371305999.
- `ubuntu-nightly` job: fixed a regression in the repo URL (introduced in PR #116)
- skip the `native:printlayouttopdf` test for QGIS 3.28.2 (segfaults in each OS where this is not skipped). This problem is being / has been addressed at QGIS (https://github.com/qgis/QGIS/issues/51383). For the time being, also 3.29 is skipped, to be revisited soon.
- fix the QGIS installation problem in the `ubuntugis` job. This has been solved by a general (cross-job) change, i.e. postponing R pkg dep installations until QGIS is installed.
- That is because the `ubuntugis` job involves adding another repo with more recent GDAL and PROJ.
- If not postponing, R pkg installation …
> Fixes in GitHub actions

- DESCRIPTION
- R/qgis-configure.R
- tests/testthat/test-qgis-configure.R
Fixes #117; follow-up for #115.
Now the presence of a commit hash is only verified in QGIS dev versions.
For QGIS dev versions with _no_ commit hash advertised (i.e. [if not built from a git repo context](https://github.com/qgis/QGIS/blob/d13a7b72787b5557860a38cdceda482a9dd4831e/cmake/CreateQgsVersion.cmake#L50)), a warning is issued and the version string will become e.g.:
`3.29.0-Master, development state unclear: exported`
Meanwhile, I noticed a segfault for the `native:printlayouttopdf` test in Linux Mint 21.1 (Ubuntu 22.04), when checking the package locally, possibly triggered by upgrading QGIS to 3.28.2. The segfault seems to occur after successfully doing the job though. `qgis_process` also throws a weird message 'Problem with SAGA installation: unsupported SAGA version (found: …
> qgis_query_version(): don't require the commit hash for regular releases

- .github/workflows/R-CMD-check.yaml
@paleolimbot I propose to run `R-CMD-check` on a weekly basis, in order to capture regressions in or incompatibilities with new QGIS releases and dev versions (the latter only in Ubuntu). What do you think?
It might be sufficient to do this only for the Ubuntu-nightly job, and apply a lower freq to the releases, but I didn't find how to differentiate scheduling between matrix configs in a simple way (it might be done by putting all steps into a reusable workflow and splitting the matrix over two caller workflows, each with another schedule => 3 instead of 1 workflow file). Further, for the releases on the three platforms it could be argued that it's difficult to predict the availability of new QGIS-packages cron-wise, given the release roadmap with some built-in irregular time steps, and …
> GHA R-CMD-check: run weekly?

- .github/workflows/R-CMD-check.yaml
- R/qgis-configure.R
- man/qgis_has_algorithm.Rd
- man/qgis_plugins.Rd
- man/qgis_run.Rd
- tests/platform-info.R
- tests/testthat/test-qgis-configure.R
Argument `debug = TRUE` (default: `FALSE`) triggers `qgis_version()` to report the output of `qgis_process --version` as messages.
This is also implemented in `tests/platform-info.R`.
```r
> qgis_version()
[1] "3.28.3-Firenze"
> qgis_version(query = TRUE)
[1] "3.28.3-Firenze"
> qgis_version(debug = TRUE)
[1] "3.28.3-Firenze"
Versions reported by 'qgis_process':
------------------------------------
QGIS 3.28.3-Firenze 'Firenze' (c12bcb2f76)
QGIS code revision c12bcb2f76
Qt version 5.15.3
Python version 3.10.6
GDAL/OGR version 3.6.2
PROJ version 9.1.1
EPSG Registry database version v10.076 (2022-08-31)
GEOS version 3.11.1-CAPI-1.17.1
SQLite version 3.37.2
OS Linux Mint 21.1
```
> qgis_version(): add argument 'debug'

- DESCRIPTION
- R/qgis-algorithms.R
- tests/testthat/test-qgis-algorithms.R
- tests/testthat/test-qgis-configure.R
This is purely for cosmetic and informational purposes.
- In the old `qgis_algorithms()` result, there were three duplicated columns (because the function code created them) and some `provider_*` columns were scattered around. This is now solved.
- `qgis_providers()` now also returns the number of algorithms per provider, turning it more into a summary of the package state. Also, sorting is now according to `provider_title` instead of `provider`, resulting in a more convenient grouping.
```r
> dplyr::glimpse(qgis_algorithms())
Rows: 785
Columns: 27
$ provider                           <chr> "3d", "cartographytools", "cartographytools", "cartographytools", "ca…
$ provider_title                     <chr> "QGIS (3D)", "Cartography tools", "Cartography tools", "Cartography t…
$ algorithm …
```
> Some modifications in the result of qgis_algorithms() and qgis_providers()

- tests/testthat/test-compat-raster.R
When doing 94de816, I didn't manage to get the WKT in the test. It seems I was using an older, separate installation of **raster** at the time.
With current **raster**, this poses no problem. So this reverts the approach of manually extracting the `projargs` slot and replaces `raster::crs()` by `raster::wkt()` as it should be.
> test-compat-raster.R: use raster::wkt()

- R/qgis-result.R
- tests/testthat/test-qgis-result.R
This allows running `qgis_result_single()` without `what` parameter, extracting the output by name or position. 
The idea is to allow extraction of single result even in cases when we don't know what type of output we want. This is related to [#JanCaha/r_package_qgis/issues/31](https://github.com/JanCaha/r_package_qgis/issues/31).
All the tests should be working :)
> Allow `qgis_result_single()` function to be runned without `what` parameter

- DESCRIPTION
- vignettes/qgisprocess.Rmd
See commit message for the list of proposed changes.
@jannes-m feel free to propose changes, or to first merge into your branch and make changes yourself.
> Proposed updates to 'basic usage' vignette

- R/qgis-algorithms.R
- R/qgis-configure.R
- R/qgis-run-algorithm.R
- man/qgis_function.Rd
- man/qgis_has_algorithm.Rd
- man/qgis_plugins.Rd
- man/qgis_run.Rd
- man/qgis_run_algorithm.Rd
Fixes #145. But ignores https://github.com/r-spatial/qgisprocess/pull/134#issuecomment-1490834960 :wink:... To be thought through further.
Plus a few documentation tweaks.
Also some roxygen-side effect (bug?) has been worked around, where an explanation of `@param .quiet` was automatically taken as explanation of the `quiet` (no dot) argument in some other functions as a consequence of `@inheritParams` (what??).
> Use .quiet=TRUE by default in qgis_run_algorithm()

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- R/qgis-state.R
- man/qgis_path.Rd
- man/vignette_childs/_qgis_expressions.Rmd
- tests/testthat/test-qgis-configure.R
- tests/testthat/test-qgis-run-algorithm2.R
- vignettes/qgis_expressions.Rmd
- handle extra plugins outside of the package source code (but at a level next to it) - in order not to bother R CMD check.
- update the R-CMD-check _ubuntugis_ job to using QGIS from the `ubuntugis-nightly-release` repo, in order to minimize QGIS installation problems when a new GRASS GIS release is out.
- add a R-CMD-check job that uses QGIS LTR, in Ubuntu. QGIS LTR had not been included in the workflow so far, but is officially supported.
Meanwhile, checking for minimal QGIS versions throughout the package has been made easier by adding a `full` argument (default `TRUE`) to `qgis_version()`. `qgis_version(full = FALSE)` just returns version number x.y.z, i.e. without the QGIS version name, so for example `"3.30.2"`.
> Update GHA workflows

- R/compat-stars.R
Handling band subsetting in `stars_proxy` objects worked differently in older versions of **stars**.
Adding support for this should solve the current CRAN check error on `r-oldrel-macos-x86_64`, for which CRAN does not offer **stars** >= 0.6-0 (due to a CRAN check error in **stars**). This error was reproduced, then solved in https://github.com/florisvdh/qgisprocess/pull/16.
> as_qgis_argument.stars_proxy(): also support stars < 0.6-0

- DESCRIPTION
- NEWS.md
- R/qgis-algorithms.R
- R/qgis-cache.R
- R/qgis-configure.R
- R/qgis-has.R
- R/qgis-plugins.R
- R/qgis-run.R
- R/qgis-state.R
- R/zzz.R
- tests/testthat/test-qgis-run.R
If for some reason `qgis_reconfigure()` is interrupted, the cache elements are set back to
`NULL` by `qgis_unconfigure()`, but `qgis_process` can possibly still be accessed.
An example was seen in https://github.com/r-spatial/qgisprocess/issues/176.
This PR adds some protection in order to maintain some package functionality
in a situation where package configuration did not succeed completely, but
`qgis_process` can be accessed nevertheless:
- making `qgis_run()` able to access the backend, will at least aid in further debugging.
- avoid erroring in `qgis_configure()` which would lead to resetting the package cache. As a result, half-configured states can emerge, but the problem of not being able to build & save the cache (which needs `has_qgis()`) is communicated to the user. Also the …
> Protect against a 'soft' package configuration failure.

- .github/ISSUE_TEMPLATE/10_package_loading.yml
- .github/ISSUE_TEMPLATE/20_plugin.yml
- .github/ISSUE_TEMPLATE/30_other.yml
- .github/ISSUE_TEMPLATE/40_feature.yml
- .github/ISSUE_TEMPLATE/config.yml
Fixes #180.
This should help users to analyze and report their problems properly, enabling developers to proceed efficiently. Setup is based on the experience with several issues in the past, and was somehow inspired by how QGIS deals with this. Different issue categories lead to a different set of questions asked.
The result has been pushed to the main branch of my fork; so you can try out at https://github.com/florisvdh/qgisprocess/issues/new/choose (screenshot below). Feel free to post some dummy issues there (posting issues in my fork will be disabled later).
**Developer community of the {qgisprocess} package**: if you're in need to add a simple housekeeping issue, e.g. a task list for yourself, use the '**feature request**' as it has the simplest form and no extra requirements. After …
> Implement issue templates

- DESCRIPTION
- NEWS.md
- R/qgis-detect.R
- tests/testthat/test-qgis-detect.R
- tests/testthat/test-qgis-state.R
Based on the request in #187. `qgis_process` file paths that contain a version number are sorted first with the highest version at the top.
> Sort file paths coming out of qgis_detect_*_paths()

- DESCRIPTION
- NEWS.md
- R/qgis-configure.R
- R/qgis-help.R
- R/qgis-state.R
- tests/testthat/test-qgis-configure.R
- tests/testthat/test-qgis-state.R
This is a follow-up to PR #192, hence issue #187.
- fix bug in support for environment variable `R_QGISPROCESS_DETECT_NEWER_QGIS`
- add test for the `qgisprocess.detect_newer_qgis` option
Further, the handling of a boolean option / environment variable is now provided by a new internal function `resolve_flag_opt()`, to avoid code duplication and mistakes.
> Fix + test for optionally detecting and proposing newer QGIS (win/mac)

- .github/workflows/R-CMD-check.yaml
It should also be noted that the r-universe runners for R-oldrel on macOS seem somewhat less reliable and need specific patching. This has been done for https://github.com/r-universe/r-spatial in 584a3db and f63925a, since that build now adds to success or failure in our main branch, but other problems for R-oldrel on macOS are still seen in https://github.com/r-universe/inbo; all having to do with processing EPSG CRSs by terra or sf it seems.
> GHA R-CMD-check: add extra CRAN-like win/mac jobs without QGIS

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- DESCRIPTION
- man/st_as_sf.Rd
- man/st_as_stars.Rd
- tests/testthat/test-compat-terra.R
In `{terra}` > 1.7-65, a SpatVector object drops its source when its CRS is overwritten (https://github.com/rspatial/terra/issues/1372).
While `qgis_as_terra()` already works fine with the changed behaviour, one of the unit tests needed updating in order to work with `{terra}` 1.7-71, just released on CRAN.
Thanks @rhijmans for bringing this to attention.
> test-compat-terra.R: let CRS comparison for SpatVector depend on {terra} version

- .zenodo.json
- CITATION.cff
- DESCRIPTION
- NEWS.md
- cran-comments.md
- inst/CITATION
Goal is to fix #203.
The `cran_submission_0.3.0` branch essentially updates the version number, pulls future updates from `main` and `cran_comments_updates` and produces new release candidates.
> Release candidate(s) for version 0.3.0

- README.md
- man/vignette_childs/_qgisprocess.Rmd
- tests/testthat/test-qgis-run-algorithm.R
- vignettes/qgisprocess.Rmd
This is needed for the pkgdown site to build once QGIS 3.36 is released in the 'ubuntu' repo of QGIS. And to fix the vignette building in R-CMD-check at that time (already broken for ubuntu-nightly QGIS).
It also checks the minimum needed QGIS version to build this vignette, in order to prevent build errors with older QGIS versions.
See https://github.com/qgis/QGIS/pull/56196 for the related QGIS update; see https://github.com/OSGeo/grass/discussions/3047 for the referred QGIS-GRASS meeting minutes.
> Vign basic: replace provider 'grass7' by 'grass' (anticipating QGIS 3.36)

- DESCRIPTION
- NEWS.md
- R/qgis-algorithms.R
- R/qgis-help.R
- R/qgis-plugins.R
- R/qgis-run-algorithm.R
- tests/testthat/test-qgis-algorithms.R
- tests/testthat/test-qgis-plugins.R
Fixes #201.
Depending on the number of installed processing provider plugins, the speed gain can be considerable!
> Speed up by using '--skip-loading-plugins' in specific 'qgis_process' calls

- DESCRIPTION
- NEWS.md
- R/qgis-run-algorithm.R
- man/qgis_run_algorithm.Rd
- man/vignette_childs/_qgis_arguments.Rmd
- vignettes/qgis_arguments.Rmd
- vignettes/qgis_options.Rmd
Two vignettes are added:
- an overview of R object classes that are accepted for each QGIS argument type, in tabular format. It is an attempt to summarize the outcomes of #13.
- an overview of available options & environment variables to configure package behaviour.
Whoever has some time, please review!
A convenient way to render them locally is by running:
```r
pkgdown::init_site()
pkgdown::build_article("qgis_arguments")
pkgdown::preview_page("articles/qgis_arguments.html")
pkgdown::build_article("qgis_options")
pkgdown::preview_page("articles/qgis_options.html")
```
This might be included in a next package release before useR! 2024; some features were already added earlier this year.
> Add vignettes on algorithm arguments + options; update qgis_run_algorithm() docs

- .zenodo.json
- CITATION.cff
- DESCRIPTION
- NEWS.md
- cran-comments.md
- inst/CITATION
Goal is to fix #214.
The `cran_submission_0.4.0` branch essentially updates the version number, pulls future updates from `main` and `cran_comments_updates` and produces new release candidates.
> Release candidate(s) for version 0.4.0

- .github/workflows/pkgdown.yaml
- pkgdown/_pkgdown.yml
- pkgdown/extra.css
- In pkgdown.yml, specify the background color of the navigation bar by using `pkgdown-navbar-bg` under `bslib`
- Modify the background color of the search box by modifying extra.css
- Synchronously update the GHA of pkgdown
> Update pkgdown.yml and extra.css to ensure that the site rendering under pkgdown2.1.0 is the same as before

- DESCRIPTION
- NEWS.md
- R/qgis-help.R
- R/qgis-run-algorithm.R
- README.Rmd
- README.md
- man/qgisprocess-package.Rd
It appears that `processx::run()` supports UTF-8 characters in all system locales (see PR #219). Also, it was observed that {qgisprocess} doesn't work successfully in non-UTF-8 locales (#218). Relaxing the UTF-8 requirement in some `qgis_run()` statements (those that set the `encoding` argument) appears to circumvent this (see #218 and PR #219), even while JSON is UTF-8 by definition.
This PR amends PR #219.
We'll see whether this would pose new problems; as of now none have been found (tests done locally in Linux Mint & Windows).
> Drop encoding = "UTF-8" for JSON in all places

- .github/workflows/pkgdown.yaml
- R/qgis-algorithms.R
This addresses and solves #218.
`qgis_run()` calls `processx::run()`.
In the documentation of the latter it says on the `encoding` argument:
>  The encoding to assume for stdout and stderr. By default the encoding of the current locale is used. Note that processx always reencodes the output of both streams in UTF-8 currently.
Hence, it seems there is no need to explicitly set the encoding. 
What do you think @florisvdh?
Or am I overlooking any unwanted side-effects?
FYI: `devtools::check()` also runs successfully with this modification.
> get rid of encoding argument

- .zenodo.json
- CITATION.cff
- DESCRIPTION
- NEWS.md
- cran-comments.md
- inst/CITATION
Goal is to fix #221.
The `cran_submission_0.4.1` branch essentially updates the version number and the `cran-comments.md` file, pulls future updates from `main`, and produces new release candidates.
> Release candidate(s) for version 0.4.1
